language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
before_script: 
  - composer install
  - cd src/tests

script: ../../vendor/bin/phpunit

notifications:
    on_success: never
    on_failure: always